### ISSUE TITLE
[Enhancement] Ability to convert videos into DS Mobiclip

### ISSUE THREAD

**Issue by DraconicNEO** [RiiConnect24/mobiclip-conversion-tool#1]
I think it would be good to include conversion for DS Mobiclip format as well in the app for the few DS apps that use Mobiclip video.
One great example of this is Dokodemo Wii no Ma.

**Comment by larsenv** [comment]
I agree, in fact it's been talked about. We have the DS Mobiclip SDK, and the encoding process is similar.

When Dokodemo comes to fruition, the converter will likely get updated.
