### ISSUE TITLE
Won't encode .mo to .mp4

### ISSUE THREAD

**Issue by Fuffley** [RiiConnect24/mobiclip-conversion-tool#3]

**Comment by noahpistilli** [comment]
That is not the point of this tool

**Comment by Artuto** [comment]
Thank you for your thorough description of your issue

**Comment by larsenv** [comment]
https://github.com/RiiConnect24/mo2mp4/releases/latest can make an mp4.

**Comment by larsenv** [comment]
https://github.com/RiiConnect24/mo2mp4/releases/latest can make an mp4.

**Comment by larsenv** [comment]
https://github.com/RiiConnect24/mo2mp4/releases/latest can make an mp4.
