### ISSUE TITLE
It encodes to 384x288 pixels instead of 640x480

### ISSUE THREAD

**Issue by DaRkProaso** [RiiConnect24/mobiclip-conversion-tool#4]
Everytime I try to convert a video, doesn't matter what resolution it is, it always converts it into 2/3 the correct resolution
![image](https://github.com/RiiConnect24/mobiclip-conversion-tool/assets/122731819/59080a63-ea3e-4f76-9702-d9f95bf12582)

**Comment by larsenv** [comment]
You will probably have to edit the VirtualDub script for it to be your desired quality.

**Comment by larsenv** [comment]
Clicked the wrong button to close an issue, I need sleep.

**Comment by DaRkProaso** [comment]
just to be sure. the file that I need to modify is the moavi.vdscript? and if so what do I need to modify to change the resolution and the Hz that the audio outputs?
![image](https://github.com/RiiConnect24/mobiclip-conversion-tool/assets/122731819/71679be9-dc25-464e-9ad0-8f3dfb189845)

**Comment by DaRkProaso** [comment]
Thanks, now it does convert properly to the res I want, but now I have another problem. No matter what I do, It always renders the audio in 48000Hz, and I want it in 32000Hz. In the convesion it's said to not change the audio Hz, but it does it anyways
![image](https://github.com/RiiConnect24/mobiclip-conversion-tool/assets/122731819/f0ffd840-29ea-4b3f-9110-f469da7dfc3a)

**Comment by larsenv** [comment]
Which audio codec you used?

**Comment by larsenv** [comment]
Why did you close it
